export const ActionType = {
    IS_LOGGEDIN: "IS_LOGGEDIN",
    IS_SIGNED_UP: "IS_SIGNED_UP",
    IS_LOGGED_OUT: "IS_LOGGED_OUT",
    IS_FETCHED_PERSONAL: "IS_FETCHED_PERSONAL",
    IS_FETCHED_WORK: "IS_FETCHED_WORK",
    IS_FETCHED_SHOPPING: "IS_FETCHED_SHOPPING",
    IS_FETCHED_CAREER: "IS_FETCHED_CAREER",
    IS_FETCHED_ALLTODOS: "IS_FETCHED_ALLTODOS",
    ADD_PERSONAL_TODO: "ADD_PERSONAL_TODO",
    ADD_CAREER_TODO: "ADD_CAREER_TODO",
    ADD_WORK_TODO: "ADD_WORK_TODO",
    ADD_SHOPPING_TODO: "ADD_SHOPPING_TODO",
};